# This workflow is triggered on pushes to the main branch.
# It deploys the website to Firebase Hosting.

name: (DEPRECATED) Deploy to Firebase Hosting on main push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "Deprecated workflow. Use .github/workflows/deploy.yml instead."